<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Expense extends Model
{
    use HasFactory, SoftDeletes;
    //
    protected $fillable = [
        'user_id',
        'category_id',
        'parent_id',
        'title',
        'type',
        'amount',
        'date',
        'description',
        'recurring_frequency',
        'recurring_start_date',
        'recurring_end_date',
        'is_auto_generated',
    ];

    protected function casts(): array
    {
        return [
            'amount' => 'decimal:2',
            'date' => 'date',
            'recurring_start_date' => 'date',
            'recurring_end_date' => 'date',
            'is_auto_generated' => 'boolean',
        ];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
    public function category(): BelongsTo{
        return $this->belongsTo(Category::class);
    }

    public function parentExpense(): BelongsTo{
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function childExpenses(): HasMany{
        return $this->hasMany(self::class, 'parent_id');
    }

    #[Scope]
    public function forUser($query, $userId): mixed
    {
        return $query->where('user_id', $userId);
    }

    #[Scope]
    public function recurring(Builder $query): Builder{
        return $query->where('type', 'recurring');
    }

    #[Scope]
    public function onTime(Builder $query): Builder{
        return $query->where('type', 'one-time');
    }

    #[Scope]
    public function inMonth(Builder $query, $month, $year): Builder{
        return $query->whereMonth('date', $month)->whereYear('date', $year);
    }

    #[Scope]
    public function inDateRange(Builder $query, $startDate, $endDate): Builder{
        return $query->whereBetween('date', [$startDate, $endDate]);
    }

    public function isRecurring(): bool{
        return $this->type === 'recurring';
    }

    public function canGenerateNextOccurrence(): bool
    {
        return $this->isRecurring() &&
            (! $this->recurring_end_date || now()->lessThanOrEqualTo($this->recurring_end_date));
    }

    public function isAutoGenerated(): bool{
        return $this->is_auto_generated === true;
    }

    public function nextOccurrenceDate(): ?Carbon{
        if (! $this->isRecurring()) {
            return null;
        }

        $lastChild = $this->childExpenses()->latest('date')->first();
        $baseDate = $lastChild ? $lastChild->date : $this->recurring_start_date;
        $baseDate = $baseDate instanceof Carbon ? $baseDate : Carbon::parse($baseDate);

        return match ($this->recurring_frequency) {
            'daily' => $baseDate->copy()->addDay(),
            'weekly' => $baseDate->copy()->addWeek(),
            'monthly' => $baseDate->copy()->addMonth(),
            'yearly' => $baseDate->copy()->addYear(),
            default => null,
        };
    }
}
